account_settings_tab.account_settings_tab_user_form:
  path: '/user/{user}/account/settings'
  defaults:
    _form: '\Drupal\account_settings_tab\Form\AccountSettingsTabForm'
    _title: 'Account Settings Tab'
  requirements:
    _user_is_logged_in: 'TRUE'