name: Account Settings Tab
type: module
description: This module provides the option to set up new tab account setting in user edit page. Which will only show the account setting details, separate the other user fields.
# core: 8.x
package: Users
features: true

# Information added by Drupal.org packaging script on 2016-02-15
version: '8.x-2.0'
core: '8.x'
project: 'account_settings_tab'
datestamp: 1455516557
